language: python
sudo: required
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python stormDetector.py
deploy:
	provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    region: us-west-2
    skip_cleanup: true
	local_dir: build/libs
	upload-dir: builds/java
