language: python

python:
  - "3.4"

install: pip install -r StormDetector/requirements.txt

script: true

before_deploy:
  - pwd
  - ls
  - zip -r SGA_TeamAurora_StormDetector.zip StormDetector appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_TeamAurora_StormDetector.zip dpl_cd_upload/SGA_TeamAurora_StormDetector.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: teamaurorabucket
    skip_cleanup: true
    local-dir: dpl_cd_upload
    upload-dir: build/libs/storm_detection
    acl: public_read
    detect_encoding: true
    on: 
      branch: feature-StormDetector
      
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: teamaurorabucket
    #key: build/libs/storm_detection/SGA_TeamAurora_StormDetector.zip
    key: SGA_TeamAurora_StormDetector.zip
    bundle_type: zip
    application: TeamAurora
    deployment_group: TeamAurora_Services
    region: us-west-2
    on:
      branch: feature-StormDetector
      

after_deploy:
  - echo "Performing after deploy procedures..."
  - done
  
notifications:
  email:
    - sriksrin@iu.edu
    - kmsheth@iu.edu
