language: java
jdk: oraclejdk8

script: mvn clean install

sudo: true

before_deploy:
  - mkdir -p data_ingestor
  - cp  ./target/dataingestor.war ./data_ingestor/dataingestor.war
  - cp -R ./scripts ./data_ingestor/scripts
  - cp -R ./docker data_ingestor/docker
  - zip -r SGA_TeamAurora_DataIngestor.zip data_ingestor appspec.yml || true
  - mkdir -p "uploadLibs"
  - mv SGA_TeamAurora_DataIngestor.zip uploadLibs/SGA_TeamAurora_DataIngestor.zip || true

deploy:
   - provider: s3
     access_key_id: $AWS_ACCESS_KEY_ID
     secret_access_key: $AWS_SECRET_ACCESS_KEY
     bucket: teamaurorabucket
     local_dir: uploadLibs
     skip_cleanup: true
     upload-dir: build/libs/data_ingestor
     region: us-west-2
     acl: public_read
     on:
        branch: Feature-DataIngestor
      
   - provider: codedeploy
     access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
     secret_access_key: $AWS_SECRET_ACCESS_KEY
     bucket: teamaurorabucket
     key: build/libs/data_ingestor/SGA_TeamAurora_DataIngestor.zip
     bundle_type: zip
     application: TeamAurora
     deployment_group: TeamAurora
     region: us-west-2
     on:
        branch: Feature-DataIngestor
