language: java
sudo: required
script: mvn clean install
branches:
    only:
        - Feature-ForecastTrigger
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    region: us-west-2
    local_dir: target
    upload-dir: builds/java
    on:
        tags: true
