language: java
jdk: oraclejdk8

script: mvn clean install

before_deploy:
  - zip -r api_gateway.zip apigateway.war || true
  - mkdir -p "uploadedLibs"
  - mv api_gateway.zip uploadedLibs/api_gateway.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    skip_cleanup: true
    local_dir: uploadedLibs
    upload-dir: build/libs/api_gateway
    on:
      branch: feature-apigateway

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    key: build/libs/api_gateway/api_gateway.zip
    bundle_type: zip
    application: TeamAurora
    deployment_group: TeamAurora
    region: us-west-2
    on:
      branch: feature-apigateway
    
notifications:
  email:
    - psanghvi@iu.edu
