language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
sudo: false
python:
  - "3.4"
branches:
  only:
    -feature-StormDetector  
before_script:
  - pip install virtualenv
  - virtualenv env
  - . env/bin/activate

install: "pip install --user -r requirements.txt"

script: python stormDetector.py

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    skip_cleanup: true
    upload-dir: builds
    on: 
      branch: Feature-StormDetector
