language: python

python:
  - "3.4"

install: pip install -r StormDetector/requirements.txt

before_script:
  - pip install virtualenv
  - cd StormDetector
  - virtualenv env
  - source env/bin/activate
  - pip install nose
  - pip install BeautifulSoup4
  - pip install Flask-SQLAlchemy

script: nosetests stormDetector.py


before_deploy:
  - cd ..
  - zip -r SGA_TeamAurora_StormDetector.zip StormDetector || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_TeamAurora_StormDetector.zip dpl_cd_upload/SGA_TeamAurora_StormDetector.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    skip_cleanup: true
    local-dir: dpl_cd_upload
    acl: public_read
    detect_encoding: true
    on: 
      branch: feature-StormDetector
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaurora
    key: SGA_TeamAurora_StormDetector.zip
    bundle_type: zip
    application: TeamAurora
    deployment_group: TeamAurora
    region: us-west-2
    on:
      branch: feature-StormDetector
notifications:
  email:
    - sriksrin@iu.edu
