language: java
jdk: oraclejdk8

script: mvn clean install

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "teamaurora"
  skip_cleanup: true
  local_dir: build/libs
  upload-dir: target
  on:
    branch: Feature-DataIngestor
    
notifications:
  email:
    - psanghvi@iu.edu
