language: java
jdk: oraclejdk8

script: mvn clean install

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    skip_cleanup: true
    region: us-west-2
    local_dir: target/ger.war
    upload-dir: builds/java
    on:
        branch: Feature-DataIngestor
