language: java
jdk: oraclejdk8
mvn test

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    region: us-west-2
    skip_cleanup: true
	local_dir: build
    