language: python
python:
  - "3.4"
install: "pip install -r requirements.txt"

script: python stormDetector.py

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    skip_cleanup: true
    upload-dir: builds
    on: 
      branch: Feature-StormDetector
