language: java
sudo: required
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "teamaurora"
    region: us-west-2
    local_dir: build/libs
    upload-dir: builds/java
branches:
    only:
        - Feature-ForeCastTrigger
