language: java
jdk: oraclejdk8

script: mvn clean install

sudo: false

before_deploy:
  #- zip -r SGA_TeamAurora_ForecastTrigger.zip ForecastTrigger.war || true
  - mkdir -p reqDir
  - cp target/ForecastTrigger.war reqDir/ForecastTrigger.war
  - cp -r ./scripts reqDir/scripts
  - cp appspec.yml reqDir/appspec.yml
  - zip -r SGA_TeamAurora_ForecastTrigger.zip reqDir || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_TeamAurora_ForecastTrigger.zip dpl_cd_upload/SGA_TeamAurora_ForecastTrigger.zip || true

deploy:
   - provider: s3
     access_key_id: $AWS_ACCESS_KEY_ID
     secret_access_key: $AWS_SECRET_ACCESS_KEY
     bucket: teamaurorabucket
     local_dir: dpl_cd_upload
     skip_cleanup: true
     upload-dir: build/libs/forecast_trigger
     region: us-west-2
     acl: public_read
     detect_encoding: true
     on:
        branch: Feature-ForecastTrigger
      
   - provider: codedeploy
     access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
     secret_access_key: $AWS_SECRET_ACCESS_KEY
     bucket: teamaurorabucket
     key: build/libs/forecast_trigger/SGA_TeamAurora_ForecastTrigger.zip
     bundle_type: zip
     application: TeamAurora
     deployment_group: TeamAurora
     region: us-west-2
     on:
        branch: Feature-ForecastTrigger
