version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: data_ingestor_worker/scripts/before_install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: data_ingestor_worker/scripts/install.sh
      timeout: 3600
      runas: root