package com.sg.aurora.common.utils;

public class Constants {
	public static final String APIGATEWAY_DATAINGESTOR_QUEUE = "APIGATEWAY_DATAINGESTOR_QUEUE";
	public static final String APIGATEWAY_STORMDETECTOR_QUEUE = "APIGATEWAY_STORMDETECTOR_QUEUE";
	public static final String APIGATEWAY_STORMCLUSTERING_QUEUE = "APIGATEWAY_STORMCLUSTERING_QUEUE";
	public static final String APIGATEWAY_FORECASTTRIGGER_QUEUE = "APIGATEWAY_FORECASTTRIGGER_QUEUE";
	public static final String APIGATEWAY_ALLSERVICES_QUEUE = "APIGATEWAY_ALLSERVICES_QUEUE";
}
